[project]
name = "tweedledum"
version = "1.1.1"
requires-python = ">=3.6"
dynamic = ["description", "readme", "license", "authors", "classifiers"]

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cmake>=3.18",
    "ninja",
    "scikit-build>=0.12.0",
]
